NewsWeek clone using boostrap
akshay-narkar/newsweek-clone pull request #6
Opened 2020-11-05 16:49 UTC by akshay-narkar

Using the bootstrap, the clone of NewsWeek was created. Different feature branches were created to work on multiple elements simultaneously.

2020-11-05 21:06 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @akshay-narkar and @wandji20 :lollipop: :balloon: 

### Thank you for your submission :handshake: :handshake: You've done a great job most of your sections are looking just like the original :star_struck: so please feel very proud of your hard work :medal_sports: :medal_sports: let's address the following changes :construction: :construction_worker: :construction_worker: 

## Page Structure

### Navigation bar
#### Desktop screens

- [x] The page is displaying 2 navigation bars and the one belonging to this screen size should be centered let's fix it, also the NEWSWEEK logo should be white like the original

- index.html
![image](https://user-images.githubusercontent.com/52209067/98280672-57303d00-1f61-11eb-96e1-5b071adc8e86.png)
- newsweek.com
![image](https://user-images.githubusercontent.com/52209067/98280760-7929bf80-1f61-11eb-9438-fcea48776b33.png)

### Subscribe and Newsletter
#### Desktop screens

- [x] These sections don't look like the original page let's fix them

- index.html
![image](https://user-images.githubusercontent.com/52209067/98282542-ff470580-1f63-11eb-981d-2de8204bd23b.png)
- newsweek.com
![image](https://user-images.githubusercontent.com/52209067/98282575-0e2db800-1f64-11eb-9d26-a50e8386b5f0.png)

#### Tablet screens

- [x] These sections should be next to each other vertically in this screen size let's fix them

- index.html
![image](https://user-images.githubusercontent.com/52209067/98283898-f48d7000-1f65-11eb-86cf-ca6b0dbf8c7a.png)
-newsweek.com
![image](https://user-images.githubusercontent.com/52209067/98283930-ff480500-1f65-11eb-9ed0-b5718499a7ad.png)

#### Mobile screens

- [x] The SUBSCRIBE section is missing the overlapping image and all the contents should be centered

- [x] The NEWSLETTER section content should also be centered and the FREE SIGN UP> button should be aligned correctly

- index.html
![image](https://user-images.githubusercontent.com/52209067/98290039-acbf1680-1f6e-11eb-9f11-87104d67dd7d.png)
- newsweek.com
![image](https://user-images.githubusercontent.com/52209067/98290073-bf395000-1f6e-11eb-9967-e2da72a7b9f9.png)

## Project Specific
### Bootstrap use

- [ ] This project is all about using bootstrap so make sure you use it for everything the less custom styling the better (it's better to have a big index.html file than big .css files)  the following are the directives I spot you used more in your stylesheet.css file and have a bootstrap option:

- width: 100%; (used 14 times) check [this](https://getbootstrap.com/docs/4.0/utilities/sizing/)
- color: black; (used 7 times) check [this](https://getbootstrap.com/docs/4.0/utilities/colors/#color)
- display: [value]; (used 25 times) check [this](https://getbootstrap.com/docs/4.0/utilities/display/)
- position: [value]; (used 14 times) check [this](https://getbootstrap.com/docs/4.0/utilities/position/)
- justify-content: [value]; (used 6 times) check [this](https://getbootstrap.com/docs/4.0/utilities/flex/#justify-content)
- text-transform: [value]; (used 16 times) check [this](https://getbootstrap.com/docs/4.0/utilities/text/#text-transform)
- font-weight: [value]; (used 27 times) check [this] (https://getbootstrap.com/docs/4.0/utilities/text/#font-weight-and-italics)
- text-align: [value]; (used 8 times) check [this](https://getbootstrap.com/docs/4.0/utilities/text/#text-alignment)
- background-color: white; (used 3 times) check [this](https://getbootstrap.com/docs/4.0/utilities/colors/#background-color)
- border-radius: [value]; (used 4 times) check [this](https://getbootstrap.com/docs/4.0/utilities/borders/#border-radius)
### CSS bad practices
> Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

#### No repeating of the same rule

- [x] Not everything can be handled by Bootstrap but let's avoid repeating rules (keep your code DRY) and create classes that can be reused within your index.html file

- background-color: #f4f5f6; (used 3 times)
- margin-top: 20px; (used 2 times)
- padding-top: 20px; (used 3 times)
- font-family: "Roboto Condensed", sans-serif; (used 2 times)
- margin-bottom: 10px; (used 4 times)
- max-width: 1310px; (used 4 times)
- margin: 0 auto; (used 3 times)
- font-size: 12px; (used 2 times)
- font-size: 16px; (used 11 times)
- margin-bottom: 0; (used 3 times)
- padding-bottom: 10px; (used 2 times)
- font-size: 15px; (used 2 times)
- height: 32px; (used 2 times)
- color: #555; (used 2 times)
- font-size: 14px; (used 5 times)
- color: #666; (used 3 times)
- text-decoration: none; (used 5 times)
- line-height: 12px; (used 2 times)

### No commented code
> Comments: It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- [x] I've put comments directly in your code where I found commented code let's delete it

### Readme file

- [x] Your Live demo is leading to a broken page let's fix it

### That's it, team! :raised_hands: 

### Please :pray: do the changes :technologist: :technologist: and submit back for a code review when you are done :memo: 

### Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-11-05 21:06 UTC, euqueme commented on stylesheet.css
> +} */
- [x] Delete the commented code

2020-11-05 21:06 UTC, euqueme commented on stylesheet.css
> +  /* padding: auto 20px; */
- [x] Delete the commented code

2020-11-05 21:06 UTC, euqueme commented on stylesheet.css
> +  /* background-color: #f8f8f8; */
- [x] Delete the commented code

2020-11-05 21:06 UTC, euqueme commented on index.html
> +            </div> -->
- [ ] Delete the commented code

2020-11-05 21:06 UTC, euqueme commented on index.html
> +            </div> -->
- [ ] Delete the comented code

2020-11-05 21:06 UTC, euqueme commented on index.html
> +            </div> -->
- [ ] Delete the comented code

2020-11-05 21:06 UTC, euqueme commented on index.html
> +        <!-- <div class="gray-border"></div> -->
- [ ] Delete the comented code

2020-11-06 18:56 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @akshay-narkar and @wandji20 :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-06 19:00 UTC, merged